Update patch set 2
Patch Set 2:

Breaks my build:
device/asus/flo/camera/QCamera2/stack/mm-camera-interface/../common/mm_camera_interface.h:34:31: fatal error: media/msmb_camera.h: No such file or directory
 #include <media/msmb_camera.h>

Patch-set: 2
Reviewer: David Marble <2644@1ec6b3db-b2c1-4fa4-84a2-4c7efe89ba71>
Label: Verified=0